### ISSUE TITLE
A few ideas

### ISSUE THREAD

**Issue by Amin456789** [cztomsik/ava#11]
Hi
first of all thank u for this lovely app
i have some idea which will be great if we can have some of them in the future

1. dark mode = playing with ava at night with dark mode will be much easier on the eyes
2. adventure mode = koboldcpp has this and it is great, please consider add this so we can play with it like a text based game
3. optimization and features from koboldcpp such as context size, context shifting [smart context]
4. changing background and avatar for our ai chat will be great too, changing our character name will be great

kind regards

**Comment by cztomsik** [comment]
FYI I am currently busy with one other project, at least for next 2 weeks, so don't expect much updates before that.

> dark mode = playing with ava at night with dark mode will be much easier on the eyes

this is already implemented, and working fine on macos, maybe it's just broken on windows.

> changing background and avatar for our ai chat will be great too, changing our character name will be great

this will definitely happen

> adventure mode = koboldcpp has this and it is great, please consider add this so we can play with it like a text based game
optimization and features from koboldcpp such as context size, context shifting [smart context]

I will consider :)

**Comment by Amin456789** [comment]
thank u so much! [to be honest i still didn't install it, so maybe it works on the windows too, i mean the dark mode] will get to it a later time, i just found ur page and was so excited about ur videos in ur program so i thought it didnt have dark mode

cant wait for ur new features, u rock!

**Comment by prabirshrestha** [comment]
darkmode does work in Windows except the title bar.

![image](https://github.com/cztomsik/ava/assets/287744/815cd199-f6be-47de-a0cb-79a95d7ba083)

here is file explorer where title bar is also dark.

![image](https://github.com/cztomsik/ava/assets/287744/ce089229-25a4-4ed8-a7c5-0740e8a715ad)

**Comment by Amin456789** [comment]
great, thank u buddy

**Comment by cztomsik** [comment]
5 was fixed, everything else is unfortunately not planned, but if you can implement it yourself, I am willing to accept PR and help with review/merging
