### ISSUE TITLE
Move overview documentation would be fabulous, this looks great. I would like to know more.

### ISSUE THREAD

**Issue by lineality** [cztomsik/ava#12]
I first found out about Ava by seeing this post on this page:
Post: "Ava is free & open-source and nobody cares, exactly as I thought before open-sourcing."
page:  https://www.reddit.com/r/LocalLLaMA/comments/193m27u/jan_an_opensource_alternative_to_lm_studio/?rdt=41906

Asside from someone (maybe a developer, or project owner?) being furiously angry and feeling hopeless, I do not have many more details about what is happening.

I have tried looking over the /cztomsik/ava github repo and doing web-searches on "Ava AI" (and it looks like there are a large number of maybe unrelated products that share the same name, or maybe some are related?), and given the growing diversity of AI tools (such as 'Open Code Interpreter' which appears to be focused on giving AI control over user and OS functions in the operating system (which is not what I expected from the name), so more like Rabbit-AI's definition of 'Action'?) it is not at all quickly obvious what the focus of a given tool is until you get a full explanation. Is this industry specific? Is this for SME's/SMB's? Is this focused on medical or municiple work? 

Please do not attack me. I am not trying to be critical, I just would like to know more about what the envisionsed use-cases, user-stories, and functionality of this tool are. Hopefully terminology and ways to share information about useful products will improve in future so contributions are not overlooked. Best of luck.

**Comment by cztomsik** [comment]
> being furiously angry and feeling hopeless

poor wording, sorry, it was not my intention to be furious

> large number of maybe unrelated products that share the same name

yes, I am aware now, I was not aware from the start (I did some quick gooling and it looked fine) but it's definitely problem now and it gets worse every week. I think the project needs new name.

> it is not at all quickly obvious what the focus of a given tool is until you get a full explanation

that's good point, originally, Ava PLS (personal) was supposed to be free, small, simple to use (including commercial usage) alternative to LM Studio. There was supposed to be premium version with things like search, RAG, ondevice fine-tuning, workflows, and also B2B version which was supposed to be premium + auth and optimizations for multi-user scenarios. All of this might still happen but I am now occupied with something else at least until Feb 2024.

> Please do not attack me. I am not trying to be critical

No worries, I'm glad for your feedback. Thanks.

**Comment by cztomsik** [comment]
Closing, the project will probably get a new name, and maybe even proper documentation (the work has started in the /docs directory) but it's not on my list right now. PRs with docs are welcome, of course.
