### ISSUE TITLE
could u please update the download section in ur website

### ISSUE THREAD

**Issue by Amin456789** [cztomsik/ava#17]
hi
as we can see u made lots of new changes that they are great in the demo videos, but the download version in ur site is lacking the new features, could u compile and update ur website please

**Comment by cztomsik** [comment]
updated, but maybe you are referring to the workflow feature and that is only available in dev build because it's not yet finished.

**Comment by Amin456789** [comment]
thank u so much, i meant the features that are in the videos in ur page

**Comment by cztomsik** [comment]
you need to double-click (either the message, or the prompt), sorry, there's no icon button for that yet

**Comment by Amin456789** [comment]
thank u
