### ISSUE TITLE
"Unexpected error: NetworkUnreachable" after clicking download on a model

### ISSUE THREAD

**Issue by quag** [cztomsik/ava#24]
I'm running on Linux. When I select Models (menu), pick a model, then pick a gguf file to download I get a "NetworkUnreachable" error. Nothing shows on stdout after the AVA welcome banner. Any tips on how to debug the problem?

```
Unexpected Error

An unexpected error occurred. (Error)

Unexpected error: NetworkUnreachable

@http://127.0.0.1:3002/app.js:71:5727
```

**Comment by cztomsik** [comment]
Sorry for the delay, there's a separate log file in your AVA_HOME directory, `log.txt` - depending on what distro you are using, it should be somewhere in `XDG_DATA_HOME/AvaPLS` or `~/.local/share/AvaPLS`.

But I'm not sure if it is going to provide anything useful, we are simply using http client from Zig ([source](https://github.com/ziglang/zig/blob/5c9eb408167672f1389c6fe58bb7851be80204de/lib/std/http/Client.zig#L1309)) so my guess is your are using proxy?
