### ISSUE TITLE
Mobile app

### ISSUE THREAD

**Issue by cztomsik** [cztomsik/ava#6]
This has been requested multiple times.

I'm not sure if we can make real mobile app because the memory constraints are too tight... (Of course this will change eventually but still, the model will be toy when compared to what you can run at home)

But we could definitely work on a responsive version of the GUI and allow some easy way to **self-host it over the SSH** or something. That way you would have "mobile app" which still needs internet, but you know all the data always stay on your computer (which needs to be running at home).

By easy way I mean having a button or some configuration screen in Settings. Because you can already do `ssh -D xxx` right now and it will work but many people don't know about this.

**Comment by 3kwa** [comment]
responsive version of the GUI hitting the self hosted API endpoints (as they mature) leveraging tailscale for the safe bridge between mobile and host
